use_frameworks!

target 'OAuthAPIKit_Example' do
  # pod 'OAuthAPIKit', :path => '../'
  pod 'OAuthAPIKit/RxSwift', :path => '../'

  target 'OAuthAPIKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 7.0'

    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest', '~> 4.0'
    pod 'RxNimble', '~> 4.0'
  end
end
