use_frameworks!

target 'APIKit_Example' do
#  pod 'APIKit', :path => '../'
  pod 'APIKit/RxSwift', :path => '../'

  target 'APIKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 7.0'

    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest', '~> 4.0'
    pod 'RxNimble', '~> 4.0'
  end
end
