# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11.2
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
     - /Users/travis/.rvm/
     - vendor/bundler

podfile: Example/Podfile

rvm:
  - 2.6.3

branches:
  only:
    - develop
    - feature/*

before_install:
  - gem install bundler:2.0.1
  - bundle install
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
  - bundle exec fastlane test
