# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2.1
language: swift
cache: cocoapods
podfile: Example/Podfile

branches:
  only:
    - develop
    - feature/*

before_install:
  - bundle install
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
  - bundle exec fastlane test
