# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane|
      # xcode_select("/Applications/Xcode 11.2.1.app")
      lanes_to_install_pods = [:test]
      if lanes_to_install_pods.include?(lane)
        puts Dir.pwd
        Dir.chdir("../Example") do
          puts Dir.pwd
          sh("ls -al")
          begin
            sh("bundle exec pod install")
          rescue
            sh("bundle exec pod install --repo-update")
          end
        end
      end
    end

  desc "Run all test cases of OAuthAPIKit"
  lane :test do
    run_tests(
      workspace: "./Example/OAuthAPIKit.xcworkspace",
      devices: ["iPhone 11 Pro"],
      scheme: "OAuthAPIKit-Example"
    )
  end

end
